name: Deploy Snowpark Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  deploy_snowflake:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_T }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_T }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_T }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_T }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_T }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_T }}
      FRED_API: ${{ secrets.FRED_API_T }}
      GCLOUD_BUCKET_NAME: ${{ secrets.GCLOUD_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Debug Environment Variables
        run: env | grep SNOWFLAKE
      
      - name: Deploy Snowpark apps
        run: python ./scripts/deploy_snowpark_apps.py $GITHUB_WORKSPACE
