name: Deploy Snowpark Apps

on:
  push:
    branches:
      - Tanmay  # ✅ Runs deploy_snowflake only when changes are pushed to this branch
  schedule:
    - cron: "*/5 * * * *"  # ✅ Runs Update_bucket every 5 minutes
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  deploy_snowflake:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_T }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_T }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_T }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_T }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_T }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_T }}
      FRED_API: ${{ secrets.FRED_API_T }}
      GCLOUD_BUCKET_NAME: ${{ secrets.GCLOUD_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Debug Environment Variables
        run: env | grep SNOWFLAKE
      
      - name: Deploy Snowpark apps
        run: python ./scripts/deploy_snowpark_apps.py $GITHUB_WORKSPACE

  Update_data:
    runs-on: ubuntu-latest
    steps:
      # Debug the event that triggered the workflow
      - name: Debug GitHub Event
        run: echo "${{ github.event_name }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests google-cloud-storage

      - name: Set up Google Cloud credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
      - name : Deug 
        run: |
            echo ${{ github.event_name }}

      - name: Run Python script to upload FRED data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API }}
          GCP_BUCKET_NAME: ${{ secrets.GCLOUD_BUCKET_NAME }}
        run: python scripts/load_raw_data.py
